version: 2.1

commands:
  step1:
    steps:
      - checkout
      - run:
          name: Step1
          command: ./step1.sh

  step2:
    steps:
      - run:
          name: Step2
          command: echo "step2"

jobs:
  job_1:
    environment:
      CIRCLE_REPOSITORY_URL: https://github.com/jacekn/test.git
    docker:
      - image: circleci/golang:1.14-stretch
    steps:
      - step1
      - step2

workflows:
  version: 2

  check_code_and_test:
    jobs:
      - job_1
