version: 2.1

commands:
  checkout:
    steps:
      - run:
          name: checkout
          command: |
            # Ensure we use https URL to clone public projects
            CIRCLE_REPOSITORY_URL=${CIRCLE_REPOSITORY_URL/://}
            CIRCLE_REPOSITORY_URL=${CIRCLE_REPOSITORY_URL/git@/https://}

            echo "Repository is: ${CIRCLE_REPOSITORY_URL}"

            # Workaround old docker images with incorrect $HOME
            # check https://github.com/docker/docker/issues/2968 for details
            if [ "${HOME}" = "/" ]
            then
              export HOME=$(getent passwd $(id -un) | cut -d: -f6)
            fi

            if [ -e /home/circleci/project/.git ]
            then
              cd /home/circleci/project
              git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
            else
              mkdir -p /home/circleci/project
              cd /home/circleci/project
              git clone "$CIRCLE_REPOSITORY_URL" .
            fi

            if [ -n "$CIRCLE_TAG" ]
            then
              git fetch --force origin "refs/tags/${CIRCLE_TAG}"
            else
              git fetch --force origin "master:remotes/origin/master"
            fi


            if [ -n "$CIRCLE_TAG" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q "$CIRCLE_TAG"
            elif [ -n "$CIRCLE_BRANCH" ]
            then
              git reset --hard "$CIRCLE_SHA1"
              git checkout -q -B "$CIRCLE_BRANCH"
            fi

            git reset --hard "$CIRCLE_SHA1"

  step1:
    steps:
      - checkout
      - run:
          name: Step1
          command: ./step1.sh

  step2:
    steps:
      - run:
          name: Step2
          command: echo "step2"

jobs:
  job_1:
    docker:
      - image: circleci/golang:1.14-stretch
    steps:
      - step1
      - step2

workflows:
  version: 2

  check_code_and_test:
    jobs:
      - job_1
